"""Interactive setup wizard — `earshot init`.

Walks a new user through configuring every channel Earshot supports and tests
credentials live as they're entered. Writes ``.env``, runs ``init-db``, and
adds at least one channel to ``channels.yaml``.

Design notes:
- Each section is skippable. Anthropic is the only hard requirement (the
  rest of the pipeline depends on Claude).
- Tests credentials immediately so the user catches a typo while they still
  have the source open, not 5 minutes later when a digest fails silently.
- ``.env`` writes are line-oriented and key-aware: re-running ``init`` updates
  values in place rather than appending duplicates.
"""
from __future__ import annotations

import os
import re
from pathlib import Path

import click

from earshot import config as config_mod, db as db_mod
from earshot.channel_resolver import ChannelResolutionError, resolve_handle


# Keys that the wizard knows how to set, in display order.
_KNOWN_KEYS = [
    "ANTHROPIC_API_KEY",
    "YAHOO_EMAIL",
    "YAHOO_APP_PASSWORD",
    "DIGEST_RECIPIENT",
    "GROQ_API_KEY",
    "TWILIO_ACCOUNT_SID",
    "TWILIO_AUTH_TOKEN",
    "TWILIO_FROM_NUMBER",
    "TWILIO_TO_NUMBER",
    "TWILIO_VOICE",
    "DIGEST_TIMEZONE",
    "DIGEST_HOUR",
    "EARSHOT_DB_PATH",
    "EARSHOT_DATA_DIR",
]


# --------------------------------------------------------------------------- #
# .env file helpers
# --------------------------------------------------------------------------- #

def _read_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    """Write keys in known order; preserve existing comments where possible.

    For simplicity, we rewrite the file from scratch with a header comment.
    Anything we don't know about gets preserved at the bottom.
    """
    known = set(_KNOWN_KEYS)
    extras = {k: v for k, v in values.items() if k not in known}
    lines: list[str] = [
        "# Earshot configuration. Generated by `earshot init`.",
        "# Edit by hand or re-run `earshot init` to update.",
        "",
    ]
    for k in _KNOWN_KEYS:
        if k in values:
            lines.append(f"{k}={values[k]}")
    if extras:
        lines.append("")
        lines.append("# user-defined")
        for k, v in extras.items():
            lines.append(f"{k}={v}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------- #
# Live credential probes
# --------------------------------------------------------------------------- #

def _check_anthropic(api_key: str) -> tuple[bool, str]:
    try:
        import anthropic
        client = anthropic.Anthropic(api_key=api_key)
        # Tiny cheap call: 1-token response to a trivial prompt.
        resp = client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=8,
            messages=[{"role": "user", "content": "Reply with the single word 'ok'."}],
        )
        if any(getattr(b, "text", "").strip() for b in resp.content):
            return True, "API key works."
        return False, "got an empty response — try a different key."
    except Exception as e:
        return False, _classify_anthropic_error(e)


def _classify_anthropic_error(exc: Exception) -> str:
    """Turn raw anthropic SDK exceptions into something a trial user can act on."""
    msg = str(exc).lower()
    cls = type(exc).__name__
    if "credit balance is too low" in msg or "insufficient_quota" in msg:
        return (
            "Anthropic credit balance too low. Add credits at "
            "https://console.anthropic.com → Plans & Billing."
        )
    if "authentication" in msg or "invalid api key" in msg or "401" in msg:
        return (
            "API key rejected (not authenticated). Double-check the key — it "
            "should start with 'sk-ant-' and have no leading/trailing whitespace."
        )
    if "rate limit" in msg or "429" in msg:
        return "Rate-limited by Anthropic. Wait a few seconds and try again."
    if isinstance(exc, (ConnectionError,)) or "name or service not known" in msg or "getaddrinfo" in msg:
        return "No network connection to Anthropic. Check your internet."
    return f"{cls}: {str(exc)[:160]}"


def _check_yahoo(email: str, password: str) -> tuple[bool, str]:
    try:
        import smtplib
        with smtplib.SMTP_SSL("smtp.mail.yahoo.com", 465, timeout=15) as s:
            s.login(email, (password or "").replace(" ", ""))
        return True, "SMTP login succeeded."
    except Exception as e:
        return False, _classify_yahoo_error(e, password)


def _classify_yahoo_error(exc: Exception, password: str) -> str:
    msg = str(exc).lower()
    cls = type(exc).__name__
    # Yahoo's SMTP auth failure for login passwords is generic 535. Heuristic:
    # if password length isn't ~16 chars (with spaces stripped), the user most
    # likely pasted a login password.
    stripped = (password or "").replace(" ", "")
    if "authenticationerror" in cls.lower() or "535" in msg:
        if 12 <= len(stripped) <= 18:
            return (
                "Yahoo rejected the app password. Double-check there are no "
                "extra characters, and that it's the latest one (generating a "
                "new one revokes previous ones)."
            )
        return (
            f"Yahoo rejected the password. This looks like a {len(stripped)}-char "
            "string — Yahoo app passwords are 16 chars. You may be using your "
            "login password instead of an app password. Generate one at "
            "login.yahoo.com → Account Security → 'Generate app password'."
        )
    if isinstance(exc, (ConnectionError,)) or "timed out" in msg or "getaddrinfo" in msg:
        return "Couldn't reach Yahoo SMTP. Check your internet."
    return f"{cls}: {str(exc)[:160]}"


def _check_groq(api_key: str) -> tuple[bool, str]:
    """Minimal probe — lists models. Doesn't transcribe anything."""
    try:
        import requests
        r = requests.get(
            "https://api.groq.com/openai/v1/models",
            headers={"Authorization": f"Bearer {api_key}"}, timeout=10,
        )
        if r.status_code == 200:
            return True, "Groq API key works."
        return False, f"HTTP {r.status_code}: {r.text[:100]}"
    except Exception as e:
        return False, f"{type(e).__name__}: {e}"


def _check_twilio(account_sid: str, auth_token: str) -> tuple[bool, str]:
    """Calls the account info endpoint — no outbound dial. Returns account status."""
    try:
        from twilio.rest import Client
        from twilio.base.exceptions import TwilioRestException
        client = Client(account_sid, auth_token)
        acct = client.api.v2010.accounts(account_sid).fetch()
        return True, f"Twilio account {acct.friendly_name} ({acct.status})."
    except Exception as e:
        return False, f"{type(e).__name__}: {e}"


# --------------------------------------------------------------------------- #
# Interactive prompts
# --------------------------------------------------------------------------- #

def _hr() -> None:
    click.echo("─" * 60)


def _prompt_with_default(label: str, default: str | None, hide: bool = False) -> str:
    if default and not hide:
        suffix = f" [{default}]"
    elif default and hide:
        suffix = " [keep existing]"
    else:
        suffix = ""
    if hide:
        val = click.prompt(f"{label}{suffix}", default="", hide_input=True, show_default=False)
        if not val:
            return default or ""
        return val.strip()
    val = click.prompt(f"{label}{suffix}", default=default or "", show_default=False)
    return val.strip()


def _ask_section(name: str, what_it_does: str, required: bool) -> bool:
    _hr()
    click.echo(click.style(f"  {name}", bold=True))
    click.echo(f"  {what_it_does}")
    if required:
        click.echo(click.style("  (required)", fg="yellow"))
        return True
    return click.confirm("  Configure this now?", default=True)


# --------------------------------------------------------------------------- #
# Channels
# --------------------------------------------------------------------------- #

def _add_channel_to_yaml(channels_path: Path, handle: str, channel_id: str, name: str) -> None:
    """Append a channel block to channels.yaml. Idempotent on channel_id."""
    text = channels_path.read_text(encoding="utf-8") if channels_path.exists() else ""
    if channel_id in text:
        return
    handle_clean = handle if handle.startswith("@") else f"@{handle}"
    block = (
        f"\n  - handle: \"{handle_clean}\"\n"
        f"    channel_id: {channel_id}\n"
        f"    name: \"{name}\"\n"
        f"    priority: 1\n"
        f"    keywords: []\n"
    )
    if not text.strip():
        text = "channels:\n"
    text = text.rstrip() + "\n" + block
    channels_path.write_text(text, encoding="utf-8")


# --------------------------------------------------------------------------- #
# Main wizard entry point
# --------------------------------------------------------------------------- #

def run_wizard() -> None:
    repo_root = config_mod.REPO_ROOT
    env_path = repo_root / ".env"
    channels_path = repo_root / "channels.yaml"

    click.echo("")
    _hr()
    click.echo(click.style("  Earshot setup", bold=True))
    _hr()
    if env_path.exists():
        click.echo(f"  Existing .env found at {env_path}. Re-running init will")
        click.echo("  let you update values; press Enter at any prompt to keep")
        click.echo("  the existing one.")
    else:
        click.echo(f"  Writing config to {env_path}")
    click.echo("")

    values: dict[str, str] = _read_env_file(env_path)

    # 1. Anthropic — REQUIRED
    if _ask_section(
        "Anthropic (Claude)",
        "Powers the episode summarizer, concept extractor, and news scorer.\n"
        "  Get a key at https://console.anthropic.com — add ~$5 of credits.",
        required=True,
    ):
        while True:
            key = _prompt_with_default(
                "  ANTHROPIC_API_KEY", values.get("ANTHROPIC_API_KEY"), hide=True,
            )
            if not key:
                click.echo(click.style("  This is required.", fg="red"))
                continue
            click.echo("  testing...")
            ok, msg = _check_anthropic(key)
            click.echo(("  " + click.style("[OK]", fg="green") + " " + msg) if ok
                       else "  " + click.style("[FAIL] ", fg="red") + msg)
            if ok or not click.confirm("  Save anyway and continue?", default=False):
                if ok:
                    values["ANTHROPIC_API_KEY"] = key
                    break
                continue
            values["ANTHROPIC_API_KEY"] = key
            break

    # 2. Yahoo SMTP — REQUIRED for email
    if _ask_section(
        "Email delivery (Yahoo SMTP)",
        "Sends the daily and instant digests.\n"
        "  YAHOO_APP_PASSWORD is generated at login.yahoo.com > Account Security\n"
        "  > 'Generate app password' — NOT your login password.",
        required=True,
    ):
        email = _prompt_with_default("  YAHOO_EMAIL", values.get("YAHOO_EMAIL"))
        if email:
            values["YAHOO_EMAIL"] = email
        pw = _prompt_with_default(
            "  YAHOO_APP_PASSWORD (16 chars, spaces ok)",
            values.get("YAHOO_APP_PASSWORD"), hide=True,
        )
        if pw:
            values["YAHOO_APP_PASSWORD"] = pw
        recipient = _prompt_with_default(
            "  DIGEST_RECIPIENT (where the email arrives)",
            values.get("DIGEST_RECIPIENT") or values.get("YAHOO_EMAIL"),
        )
        if recipient:
            values["DIGEST_RECIPIENT"] = recipient

        if email and pw:
            click.echo("  testing SMTP login...")
            ok, msg = _check_yahoo(email, pw)
            click.echo(("  " + click.style("[OK]", fg="green") + " " + msg) if ok
                       else "  " + click.style("[FAIL] ", fg="red") + msg)
            if not ok:
                click.echo("  Saving anyway — fix the password later and re-run init.")

    # 3. Groq — OPTIONAL (ASR fallback)
    if _ask_section(
        "Groq Whisper (optional)",
        "Audio transcription fallback when a YouTube video has no captions.\n"
        "  Almost never fires in practice. Free tier at https://console.groq.com.",
        required=False,
    ):
        key = _prompt_with_default("  GROQ_API_KEY", values.get("GROQ_API_KEY"), hide=True)
        if key:
            values["GROQ_API_KEY"] = key
            click.echo("  testing...")
            ok, msg = _check_groq(key)
            click.echo(("  " + click.style("[OK]", fg="green") + " " + msg) if ok
                       else "  " + click.style("[FAIL] ", fg="red") + msg)

    # 4. Twilio — OPTIONAL (voice channel, v1.5)
    if _ask_section(
        "Twilio voice channel (optional, v1.5)",
        "Outbound phone call that reads a ~90-second voice-tailored digest.\n"
        "  Get creds at https://console.twilio.com. ~$1/mo for a number + ~$0.02/day.\n"
        "  Trial accounts require the TO number to be verified in Twilio's console.",
        required=False,
    ):
        sid = _prompt_with_default("  TWILIO_ACCOUNT_SID", values.get("TWILIO_ACCOUNT_SID"))
        if sid:
            values["TWILIO_ACCOUNT_SID"] = sid
        tok = _prompt_with_default("  TWILIO_AUTH_TOKEN", values.get("TWILIO_AUTH_TOKEN"), hide=True)
        if tok:
            values["TWILIO_AUTH_TOKEN"] = tok
        frm = _prompt_with_default("  TWILIO_FROM_NUMBER (+1...)", values.get("TWILIO_FROM_NUMBER"))
        if frm:
            values["TWILIO_FROM_NUMBER"] = frm
        to = _prompt_with_default("  TWILIO_TO_NUMBER (+1...)", values.get("TWILIO_TO_NUMBER"))
        if to:
            values["TWILIO_TO_NUMBER"] = to
        voice = _prompt_with_default(
            "  TWILIO_VOICE",
            values.get("TWILIO_VOICE", "Polly.Joanna"),
        )
        if voice:
            values["TWILIO_VOICE"] = voice

        if sid and tok:
            click.echo("  testing Twilio account...")
            ok, msg = _check_twilio(sid, tok)
            click.echo(("  " + click.style("[OK]", fg="green") + " " + msg) if ok
                       else "  " + click.style("[FAIL] ", fg="red") + msg)

    # 5. Schedule preferences
    if _ask_section(
        "Schedule",
        "Timezone the digest_local date is computed in, and the hour the\n"
        "  Windows Task Scheduler will fire (you'll set this up via `earshot\n"
        "  schedule` after init finishes).",
        required=False,
    ):
        tz = _prompt_with_default("  DIGEST_TIMEZONE", values.get("DIGEST_TIMEZONE", "America/New_York"))
        if tz:
            values["DIGEST_TIMEZONE"] = tz
        hour = _prompt_with_default("  DIGEST_HOUR (0-23, local time)", values.get("DIGEST_HOUR", "12"))
        if hour:
            values["DIGEST_HOUR"] = hour

    # Write .env
    _hr()
    _write_env_file(env_path, values)
    click.echo(f"  Wrote {env_path}")

    # 6. Init DB
    cfg = config_mod.load(dotenv_path=env_path)
    if not cfg.db_path.exists():
        click.echo(f"  Initializing database at {cfg.db_path}...")
        conn = db_mod.connect(cfg.db_path)
        db_mod.init_schema(conn)
        conn.close()
        click.echo("  DB ready.")
    else:
        click.echo(f"  Database already exists at {cfg.db_path}, leaving it alone.")

    # 7. Channels
    _hr()
    click.echo(click.style("  Channels", bold=True))
    click.echo("  At least one YouTube channel to monitor. Paste an @handle")
    click.echo("  (e.g. @AIDailyBrief). Press Enter on a blank line to finish.")
    existing_handles = {c.handle.lower() for c in cfg.channels}
    if existing_handles:
        click.echo(f"  Already configured: {', '.join(sorted(existing_handles))}")
    added = 0
    while True:
        handle = click.prompt("  add @handle (blank to stop)", default="", show_default=False).strip()
        if not handle:
            break
        if not handle.startswith("@"):
            handle = "@" + handle
        if handle.lower() in existing_handles:
            click.echo(f"  {handle} already in channels.yaml — skipping.")
            continue
        try:
            channel_id, name = resolve_handle(handle)
        except ChannelResolutionError as e:
            click.echo(click.style(f"  could not resolve: {e}", fg="red"))
            continue
        _add_channel_to_yaml(channels_path, handle, channel_id, name)
        existing_handles.add(handle.lower())
        added += 1
        click.echo(click.style(f"  added {handle} -> {channel_id} ({name})", fg="green"))

    if added == 0 and not existing_handles:
        click.echo(click.style(
            "  No channels added. Run `earshot resolve-channel @handle` later\n"
            "  and paste the block into channels.yaml before scheduling.",
            fg="yellow",
        ))

    # Final health check — same probes as `earshot doctor` so the user
    # sees red/green before exiting the wizard.
    _hr()
    click.echo(click.style("  Health check", bold=True))
    cfg = config_mod.load(dotenv_path=env_path)
    from earshot import doctor as doctor_mod
    n_fail = n_warn = 0
    for r in doctor_mod.run_all(cfg):
        if r.status == "ok":
            mark = click.style("[OK]  ", fg="green")
        elif r.status == "warn":
            mark = click.style("[WARN]", fg="yellow"); n_warn += 1
        elif r.status == "fail":
            mark = click.style("[FAIL]", fg="red"); n_fail += 1
        else:
            mark = click.style("[--]  ", fg="white")
        click.echo(f"  {mark}  {r.name:14s}  {r.message}")
        if r.hint and r.status in ("warn", "fail"):
            click.echo(f"          hint: {r.hint}")

    _hr()
    if n_fail:
        click.echo(click.style(
            f"  Setup wrote .env, but {n_fail} check(s) failed.", bold=True, fg="yellow",
        ))
        click.echo("  Fix the failing items above (hints in each line), then re-run:")
        click.echo("    earshot doctor")
    else:
        click.echo(click.style("  Setup complete.", bold=True, fg="green"))
    click.echo("")
    click.echo("  Next steps:")
    click.echo("    1. Try it now:        earshot run")
    click.echo("    2. Schedule daily:    earshot schedule")
    click.echo("    3. Diagnose issues:   earshot doctor")
    click.echo("")
